### ISSUE TITLE
Make 'select variable' drop down list use recognizable variable names

### ISSUE THREAD

**Issue by jharcum** [tetratech/baytrendsmap#18]
**Describe the solution you'd like**
Make 'select variable' drop down list use recognizable variable names. see screen capture.

![image](https://user-images.githubusercontent.com/13320765/82078206-c1e97580-96ae-11ea-8969-0d26410c4fc9.png)

**Comment by leppott** [comment]
Change pick_gamDiff to pick_gamDiff_Desc in server.R

![image](https://user-images.githubusercontent.com/24276278/83970408-93bd1700-a8a3-11ea-8c12-ad08c24bede6.png)

![image](https://user-images.githubusercontent.com/24276278/83970420-a1729c80-a8a3-11ea-8e12-4dcf97980d7f.png)

**Comment by leppott** [comment]
![image](https://user-images.githubusercontent.com/24276278/83970456-c9620000-a8a3-11ea-9774-c03fc871ae8c.png)

**Comment by leppott** [comment]
Change mr_var and mr_var_name in Server.R.  

Swamp how select since swapped selectize input from Variable to Description.

**OLD**
![image](https://user-images.githubusercontent.com/24276278/83970560-47bea200-a8a4-11ea-8ce0-5484e12f5219.png)

**Revised**
![image](https://user-images.githubusercontent.com/24276278/83970594-848a9900-a8a4-11ea-8e28-a9e48dfc91b5.png)

**Comment by leppott** [comment]
![image](https://user-images.githubusercontent.com/24276278/83970619-a6841b80-a8a4-11ea-81a3-250f73cc07fa.png)

**Comment by jharcum** [comment]
Tested. Appears Correct.
